name: "Test Branches"

on:
  push:
    branches:
      - '**'
      - '!main' 
  workflow_dispatch:

jobs:
  release:
    name: "Test Branch ${{ github.ref }}"
    runs-on: ubuntu-latest

    steps:
      -
        name: "Checkout source code"
        uses: "actions/checkout@v3.1.0"
        with:
          ref: ${{ github.ref }}
      -
        name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      -
        name: Update packages
        run: sudo apt update -qq
      - 
        name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unzip \
            ca-certificates \
            build-essential \
            ccache \
            cmake \
            g++-10 \
            libc++-9-dev \
            libc++abi-9-dev \
            ninja-build \
            wget \
            pkg-config \
            xvfb \
            libglfw3-dev \
            libuv1-dev \
            libjpeg-turbo8 \
            libicu66 \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            libcurl4-openssl-dev \
            libpixman-1-dev
      -
        name: Install node dependencies
        run: npm install
      - 
        name: Download test data
        run: wget -O test_data.zip https://github.com/acalcutt/tileserver-gl/releases/download/test_data/test_data.zip
      -
        name: Unzip test data
        run: unzip -q test_data.zip -d test_data
      -
        name: Run tests
        run: xvfb-run --server-args="-screen 0 1024x768x24" npm test
